# Generated by Django 3.2.4 on 2021-06-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='author',
        ),
    ]
