# Generated by Django 3.2.4 on 2021-06-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Number',
            field=models.IntegerField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
